version: '3'

services:
  exemplo:
    build: .
    image: exemplo
    container_name: exemplo-backend
    ports:
    - "6000:80"
    restart: always
    environment:
      ConnectionStrings__ExemploDbContext: "Server=host.docker.internal,1533;Database=Exemplo;User Id=sa;Password=Your_password123;Integrated Security=false;TrustServerCertificate=True;"
      ConnectionStrings__ConnectionRedis: "host.docker.internal:6390,password=qwe123*,abortConnect=false"
      ValidoEm: "http://host.docker.internal"
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - exemplo:/app/data
  redis:
    image: redis
    container_name: redis-exemplo
    command: redis-server --requirepass qwe123*
    ports:
      - "6390:6389"

volumes:
  exemplo:
